const RecurringTransactionActionTypes = {
    SET_RECURRING_TRANSACTIONS: 'SET_RECURRING_TRANSACTIONS',
    ADD_RECURRING_TRANSACTION: 'ADD_RECURRING_TRANSACTION',
    UPDATE_RECURRING_TRANSACTIONS: 'UPDATE_RECURRING_TRANSACTIONS',
    DELETE_RECURRING_TRANSACTION: 'DELETE_RECURRING_TRANSACTION',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default RecurringTransactionActionTypes;