const TransactionActionTypes = {
    SET_TRANSACTIONS: 'SET_TRANSACTIONS',
    RECONCILE_TRANSACTION: 'RECONCILE_TRANSACTION',
    SET_TRANSACTIONS_NOT_RECONCILED: 'SET_TRANSACTIONS_NOT_RECONCILED',
    ADD_TRANSACTION: 'ADD_TRANSACTION',
    UPDATE_TRANSACTIONS: 'UPDATE_TRANSACTIONS',
    DELETE_TRANSACTION: 'DELETE_TRANSACTION',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default TransactionActionTypes;