const AccountActionTypes = {
    SET_ACCOUNTS: 'SET_ACCOUNTS',
    SET_ALL_ACCOUNTS: 'SET_ALL_ACCOUNTS',
    SET_SINGLE_ACCOUNT: 'SET_SINGLE_ACCOUNT',
    ADD_ACCOUNT: 'ADD_ACCOUNT',
    UPDATE_ACCOUNTS: 'UPDATE_ACCOUNTS',
    UPDATE_BANK_ACCOUNT: 'UPDATE_BANK_ACCOUNT',
    DELETE_ACCOUNT: 'DELETE_ACCOUNT',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default AccountActionTypes;