const AccountActionTypes = {
    SET_ACCOUNTS: 'SET_ACCOUNTS',
    SET_ALL_ACCOUNTS: 'SET_ALL_ACCOUNTS',
    SET_SELECTED_ACCOUNT: 'SET_SELECTED_ACCOUNT',
    SET_SELECTED_TO_BANK_ACCOUNT: 'SET_SELECTED_TO_BANK_ACCOUNT',
    ADD_ACCOUNT: 'ADD_ACCOUNT',
    UPDATE_ACCOUNTS: 'UPDATE_ACCOUNTS',
    UPDATE_BANK_ACCOUNT: 'UPDATE_BANK_ACCOUNT',
    UPDATE_ACCOUNT_BALANCE: 'UPDATE_ACCOUNT_BALANCE',
    DELETE_ACCOUNT: 'DELETE_ACCOUNT',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default AccountActionTypes;